from os import path
from glob import glob
import fabio
from fragview.fileio import makedirs
from fragview.projects import project_fragmax_dir, project_raw_protein_dir, project_process_protein_dir


def generate_meta_xml_files(project):
    raw_cbf_folder = project_raw_protein_dir(project)
    fragmax_dir = project_fragmax_dir(project)

    for dataset in sorted(glob(f"{raw_cbf_folder}/*"), key=lambda x: ("Apo" in x, x)):
        dts = dataset.split("/")[-1]
        runs = set([cbf_filename.split("_")[-2] for cbf_filename in
                    glob(f"{dataset}/{project.protein}*cbf")])
        for run in runs:
            dataset = f"{dts}_{run}"
            cbf_range = sorted(glob(f"{raw_cbf_folder}/{dts}/{dataset}_*.cbf"))
            cbf_ini, cbf_end = cbf_range[::len(cbf_range) - 1]
            file = path.join(fragmax_dir, "process", project.protein, dts, f"{dataset}.xml")
            _create_xml_file(project, dataset, cbf_ini, cbf_end)
            yield file


def _create_xml_file(project, dataset, cbf_ini, cbf_end):
    """
    generate a XML file from CBF files. It is similar to what is generated by MAX IV for ISPyB
    """
    def format_e(n):
        a = '%E' % n
        return a.split('E')[0].rstrip('0').rstrip('.') + 'E' + a.split('E')[1]

    with fabio.open(cbf_ini) as img:
        file_i = img.header["_array_data.header_contents"].splitlines()

    with fabio.open(cbf_end) as img:
        file_e = img.header["_array_data.header_contents"].splitlines()

    cbf = [x.rstrip().replace("# ", "") for x in file_i]
    cbf_e = [x.rstrip().replace("# ", "") for x in file_e]

    axisEnd = 0
    axisStart = float(cbf[10].split()[1]) * float(cbf[7].split()[1])
    beamSizeAtSampleX = format_e(float(cbf[11].split()[1][1:-1]) / 1000)
    beamSizeAtSampleY = format_e(float(cbf[11].split()[2][:-1]) / 1000)
    dataCollectionNumer = cbf_ini.split("_")[-2]
    detectorDistance = format_e(float(cbf[16].split()[1]) * 1000)
    detectorModel = " ".join(cbf[0].split()[1:3]).replace(",", "")
    if detectorModel == "PILATUS3 2M":
        detectorType = "Hybrid Photon Counting"
        experimentBeamline = "BESSY II 14.2"
    elif detectorModel == "PILATUS3 6M":
        detectorType = "Hybrid Photon Counting"
        experimentBeamline = "BESSY II 14.2"
    else:
        detectorType = "Unknown"
        experimentBeamline = "Unknown"

    X = cbf[2].split()[1]
    Y = cbf[2].split()[4]
    detectorPixelSize = "{:.3f}".format(float(X) * 1000) + " mm x " + "{:.3f}".format(float(Y) * 1000) + " mm"
    endTime = cbf_e[1]
    exposureTime = format_e(float(cbf[12].split()[1]))
    fileTemplate = "_".join(cbf_ini.split("/")[-1].split("_")[:-1]) + "_%04d.cbf"
    flux = cbf[27].split()[1]
    imagePrefix = dataset.split("_")[0]
    imageDirectory = f"/data/fragmaxrpc/user/{project.proposal}/raw/{project.protein}/{imagePrefix}"
    numberOfImages = cbf[10].split()[1]
    resolution = format_e(float(cbf[16].split()[1]) * 8.178158027176648)
    slitGapHorizontal = "0.0"
    slitGapVertical = "0.0"
    startTime = cbf[1]
    synchrotronMode = ""
    transmission = format_e(float(cbf[25].split()[1]))
    wavelength = format_e(float(cbf[30].split()[1]))
    xtalSnapshotFullPath1 = "None"
    xtalSnapshotFullPath2 = "None"
    detector2theta = format_e(float(cbf[26].split()[1]))
    rotationAxis = cbf[4].split()[1]

    xml = f"""<?xml version="1.0" ?>
    <XSDataResultRetrieveDataCollection>
        <dataCollection>
            <actualCenteringPosition> sampx=0 sampy=0 phi=0.000000 focus=0 phiz=0 phiy=0</actualCenteringPosition>
            <detectorModel>{detectorModel}</detectorModel>
            <detectorType>{detectorType}</detectorType>
            <detectorPixelSize>{detectorPixelSize}</detectorPixelSize>
            <experimentBeamline>{experimentBeamline}</experimentBeamline>
            <axisEnd>{axisEnd}</axisEnd>
            <axisRange>0.000000e+00</axisRange>
            <axisStart>{axisStart}</axisStart>
            <beamShape>ellipse</beamShape>
            <beamSizeAtSampleX>{beamSizeAtSampleX}</beamSizeAtSampleX>
            <beamSizeAtSampleY>{beamSizeAtSampleY}</beamSizeAtSampleY>
            <centeringMethod>None</centeringMethod>
            <comments>None</comments>
            <crystalClass>None</crystalClass>
            <dataCollectionId>None</dataCollectionId>
            <dataCollectionNumber>{dataCollectionNumer}</dataCollectionNumber>
            <detector2theta>{detector2theta}</detector2theta>
            <detectorDistance>{detectorDistance}</detectorDistance>
            <detectorMode>None</detectorMode>
            <endTime>{endTime}</endTime>
            <exposureTime>{exposureTime}</exposureTime>
            <experimentType>None</experimentType>
            <fileTemplate>{fileTemplate}</fileTemplate>
            <flux>{flux}</flux>
            <imageDirectory>{imageDirectory}</imageDirectory>
            <imagePrefix>{imagePrefix}</imagePrefix>
            <imageSuffix>cbf</imageSuffix>
            <kappaStart>0.000000e+00</kappaStart>
            <numberOfImages>{numberOfImages}</numberOfImages>
            <numberOfPasses>1</numberOfPasses>
            <overlap>0.000000e+00</overlap>
            <phiStart>0.000000e+00</phiStart>
            <printableForReport>false</printableForReport>
            <resolution>{resolution}</resolution>
            <rotationAxis>{rotationAxis}</rotationAxis>
            <runStatus>Data collection successful</runStatus>
            <slitGapVertical>{slitGapVertical}</slitGapVertical>
            <slitGapHorizontal>{slitGapHorizontal}</slitGapHorizontal>
            <startImageNumber>1</startImageNumber>
            <startTime>{startTime}</startTime>
            <synchrotronMode>{synchrotronMode}</synchrotronMode>
            <transmission>{transmission}</transmission>
            <wavelength>{wavelength}</wavelength>
            <xbeam>0.00000e+00</xbeam>
            <xtalSnapshotFullPath1>{xtalSnapshotFullPath1}</xtalSnapshotFullPath1>
            <xtalSnapshotFullPath2>{xtalSnapshotFullPath2}</xtalSnapshotFullPath2>
            <xtalSnapshotFullPath3>None</xtalSnapshotFullPath3>
            <xtalSnapshotFullPath4>None</xtalSnapshotFullPath4>
            <ybeam>0.00000e+00</ybeam>
        </dataCollection>
    </XSDataResultRetrieveDataCollection>"""

    dst_dir = path.join(project_process_protein_dir(project), imagePrefix)
    dstxml = path.join(dst_dir, f"{dataset}.xml")

    makedirs(dst_dir)
    with open(dstxml, "wb") as xmlFile:
        xmlFile.write(xml.encode())
