# Generated by Django 2.2.1 on 2019-10-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.TextField()),
                ('library', models.TextField()),
                ('proposal', models.TextField()),
                ('shift', models.TextField()),
                ('shift_list', models.TextField(blank=True)),
            ],
        ),
    ]
