# Generated by Django 3.2.10 on 2022-05-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fragview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="project_id",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="library",
            name="name",
            field=models.TextField(),
        ),
    ]
